
# A Beginner's Guide to NumPy


It is the fundamental package for scientific computing with Python.

- np.array
- np.concatenate
- np.ones
- np.matmul
- np.eye

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [14]:
import numpy as np

In [15]:
# List of functions explained 
function1 = np.array
function2 = np.concatenate
function3 = np.ones
function4 = np.matmul
function5 = np.eye

"""
Add your function name here
"""

'\nAdd your function name here\n'

## Function 1 - np.array

- This function creates an (n-dimensional) array out of a normal python list.

In [16]:
# Example 1 - working 
np.array([[5,10,15,20],[3,6,9,12]])

array([[ 5, 10, 15, 20],
       [ 3,  6,  9, 12]])

- A 2-d array out of a nested list.

In [17]:
# Example 2 - working 
np.array([[1,2,3,4,5],[6,7,8,9,10.0]])

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

- Upcasting : When a single element of the array is of float type than all the elements are upcasted to float type.

In [18]:
np.array([[1,2,3],[4,5]],dtype=int)

ValueError: setting an array element with a sequence.

- Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If we still wanted to make an array we should assign *dtype=object*

- A numpy array has obvious advantages over a normal python list.

## Function 2 - np.concatenate

- This function joins a sequence of arrays along an existing axis.

In [19]:
# Example 1 - working 
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

- Concatenating two arrays along *axis=1*

In [20]:
# Example 2 - working
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

- Concatenating two arrays when *axis=None*. If axis is None, arrays are flattened before use.

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

- Since, the array along dimensioon 1 index 0 has 2 elements and the array along index 1 has size 3. All the input array dimensions for the concatenation axis must match exactly.

- It is a useful function to join 2 functions.

## Function 3 - np.ones

- This function returns a new array of given shape and type, filled with ones.

In [24]:
# Example 1 - working
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

- 1-d array 

In [25]:
# Example 2 - working
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

- 2-d array with floating point.

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
np.ones(3,4)

TypeError: data type not understood

- Shape of the array should be provided within parantheses.

- It is used to form an identity matrix.

## Function 4 - np.matmul

- This function returns matrix product of two arrays.

In [26]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)


array([[4, 1],
       [2, 2]])

- Matrix Multiplication of two 2-d arrays.

In [27]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([1, 2])
np.matmul(a, b)

np.matmul(b, a)

array([1, 2])

- The matmul function implements the semantics of the @ operator introduced in Python 3.5 

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
np.matmul([1,2], 3)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

- Scalar multiplication raises an error.

- This function is useful for matrix multiplication of two matrices or vectors.

## Function 5 - np.eye

- This function returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- Creates a 5-d diagonal matrix.

In [30]:
np.eye(3,5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

- Creates a 3x5 array with int type elements.

In [31]:
np.eye(2,3.5,dtype=float)

TypeError: 'float' object cannot be interpreted as an integer

- A matrix can't have a floating point dimension.

- np.eye is , generally, used to form a diagonal matrix.

## Conclusion

We covered 5 interesting functions from the NumPy library, namely,

- np.array
- np.concatenate
- np.ones
- np.matmul
- np.eye

Since I'm not a good teacher so, I didnt covered each topic exhaustively. 
There are many resources out there to refer to for more depth understanding.
If you want to dig deep, check out the **Resources & References** section below.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html


### Framework / skeleton for contribution
#### Pleasse dont delete these cell blocks


## Function 6 - < function-name >

- < A small definition/description of the function >

In [32]:
#Example 1



- A small description / use of the function

In [33]:
#Example 2



- A small description / use of the function

In [34]:
#Example 3 aka the "code-phat-gya" example



- Remedy / solution to fix the issue or a definition

- Conclusion: < Your viewpoint/ a use case of the example.

In [ ]:
"""
Add your code cells below this cell...
DO NOT DELETE ABOVE CODE CELLS...
"""